// <auto-generated />
using System;
using Anketa_4_core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anketa_4_core.Migrations
{
    [DbContext(typeof(AnketaContext))]
    [Migration("20231003100933_ank_migr_02")]
    partial class ank_migr_02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.AccessForTestable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("TestPeriodID")
                        .HasColumnType("integer");

                    b.Property<int>("TestableID")
                        .HasColumnType("integer");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("TestPeriodID");

                    b.HasIndex("TestableID");

                    b.ToTable("AccessForTestables");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Comp_Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Correct_Answer")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionID")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Comp_Answers");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Comp_Block", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("BlockName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WordInReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Comp_Blocks");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Comp_Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("BlockID")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BlockID");

                    b.ToTable("Comp_Questions");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Comp_TestableAnswer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AccessID")
                        .HasColumnType("integer");

                    b.Property<int>("AnswerID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTimeAnswer")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mark")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AccessID");

                    b.HasIndex("AnswerID");

                    b.ToTable("Comp_TestableAnswers");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Filial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("FilialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Filials");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AnswerNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("KT_Answers");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("KT_Categories");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_KeyForCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AnswerID")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AnswerID");

                    b.HasIndex("CategoryID");

                    b.ToTable("KT_Keys");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_Main", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AccessID")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Years")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AccessID");

                    b.ToTable("KT_Mains");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_Mark", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<string>("LevelWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LevelWordInReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mark")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreFrom")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreTo")
                        .HasColumnType("integer");

                    b.Property<string>("WordInReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("KT_Marks");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("KT_Questions");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_TestableAnswers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AnswerID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTimeAnswer")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MainInfoID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AnswerID");

                    b.HasIndex("MainInfoID");

                    b.ToTable("KT_TestableAnswers");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.MotivationTest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AccessTestID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatetimeTest")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAgree")
                        .HasColumnType("boolean");

                    b.Property<string>("Results")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AccessTestID");

                    b.ToTable("MotivationTests");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.News", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateNews")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.ReservLevel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ReservLevelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("ReservLevels");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.RespondentRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isSelfMark")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("RespondentRoles");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Test360", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AccessTestID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatetimeTest")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSelfMark")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<string>("results")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AccessTestID");

                    b.HasIndex("RoleID");

                    b.ToTable("Test360");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.TestPeriod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("TestPeriods");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.TestResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AccessID")
                        .HasColumnType("integer");

                    b.Property<string>("Results")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AccessID");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Testable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearTraining")
                        .HasColumnType("integer");

                    b.Property<int>("filialID")
                        .HasColumnType("integer");

                    b.Property<bool>("isArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("reservLevelID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("filialID");

                    b.HasIndex("reservLevelID");

                    b.ToTable("Testables");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.TestableUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("LK_Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("testableID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("testableID");

                    b.ToTable("TestableUsers");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.AccessForTestable", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.TestPeriod", "TestPeriod")
                        .WithMany()
                        .HasForeignKey("TestPeriodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anketa_4_core.Data.AnketaModels.Testable", "Testable")
                        .WithMany()
                        .HasForeignKey("TestableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestPeriod");

                    b.Navigation("Testable");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Comp_Answer", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.Comp_Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Comp_Question", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.Comp_Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Comp_TestableAnswer", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.AccessForTestable", "Access")
                        .WithMany()
                        .HasForeignKey("AccessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anketa_4_core.Data.AnketaModels.Comp_Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("Answer");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_Answer", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.KT_Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_KeyForCategory", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.KT_Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anketa_4_core.Data.AnketaModels.KT_Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_Main", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.AccessForTestable", "Access")
                        .WithMany()
                        .HasForeignKey("AccessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_Mark", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.KT_Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.KT_TestableAnswers", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.KT_Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anketa_4_core.Data.AnketaModels.KT_Main", "MainInfo")
                        .WithMany()
                        .HasForeignKey("MainInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("MainInfo");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.MotivationTest", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.AccessForTestable", "AccessTest")
                        .WithMany()
                        .HasForeignKey("AccessTestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessTest");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Test360", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.AccessForTestable", "AccessTest")
                        .WithMany()
                        .HasForeignKey("AccessTestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anketa_4_core.Data.AnketaModels.RespondentRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessTest");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.TestResult", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.AccessForTestable", "Access")
                        .WithMany()
                        .HasForeignKey("AccessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.Testable", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.Filial", "filial")
                        .WithMany()
                        .HasForeignKey("filialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anketa_4_core.Data.AnketaModels.ReservLevel", "reservLevel")
                        .WithMany()
                        .HasForeignKey("reservLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("filial");

                    b.Navigation("reservLevel");
                });

            modelBuilder.Entity("Anketa_4_core.Data.AnketaModels.TestableUser", b =>
                {
                    b.HasOne("Anketa_4_core.Data.AnketaModels.Testable", "testable")
                        .WithMany()
                        .HasForeignKey("testableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("testable");
                });
#pragma warning restore 612, 618
        }
    }
}
